### ISSUE TITLE
Non-existant constant

### ISSUE THREAD

**Issue by BinarMorker** [Youmy001/apine_framework#1]
In the class [ApineUser](https://github.com/Youmy001/apine_framework/blob/master/lib/model/user.php), the method "get_register_date" refers to a non-existant constant, APP_DATE_FORMAT. Data format should be defined in the config.

**Comment by Youmy001** [comment]
Thanks for your feedback. A fix will be included in our next commit. Meanwhile, you can replace the constant by that string :  "Y-M-D H:m:s".
