### ISSUE TITLE
ApineFileImage is broken

### ISSUE THREAD

**Issue by BinarMorker** [Youmy001/apine_framework#11]
ApineFileImage does not follow the same structure as ApineFile, and the functions used in ApineFileImage do not work anymore with its parent. Therefore, the class should use a rewrite in my opinion.

**Comment by Youmy001** [comment]
What do you mean by "should use a rewrite"? And also can you give us more details on errors you are getting with ApineFileImage?

**Comment by Youmy001** [comment]
We indeed found many issues inside ApineFileImage. We found that it wasn't saving properly modifications, cropping was actually resizing and there was issues with load the resource.

**Comment by Youmy001** [comment]
Considering there's no further comments, I close this issue.
