### ISSUE TITLE
Bad query

### ISSUE THREAD

**Issue by BinarMorker** [Youmy001/apine_framework#2]
In the class [ApineUserFactory](https://github.com/Youmy001/apine_framework/blob/master/lib/model/factory/user_factory.php), the method "create_by_group" contains a bad SQL query. Normally, ```"SELECT ID from `apine_users` where group=$group"``` would work. In this case, the keyword "group" in reserved in MySQL and is therefore not considered a column name, but that specific keyword and thus the query fails. The query should be replaced by ```"SELECT ID from `apine_users` where `group`=$group"```.

**Comment by Youmy001** [comment]
Thanks for your feedback. A fix will be included in our next commit.
