### ISSUE TITLE
Add custom port support

### ISSUE THREAD

**Issue by Youmy001** [Youmy001/apine_framework#3]
Many modules in the framework currently implies the request come from the default http and https ports. When testing with custom ports the application will fail to generate valid links and **return 404 response**.

Plausible addition point would be inside *Request* and *URLHelper* classes.

**Comment by BinarMorker** [comment]
I managed to modify the "write_url" method in URL_Helper:
```
private static function write_url($path){
	return self::get_instance()->session_server . (($_SERVER['SERVER_PORT']!=80 && $_SERVER['SERVER_PORT']!=443)?":".$_SERVER['SERVER_PORT']:"") . '/' . $path;
}
```

**Comment by Youmy001** [comment]
Thanks for your feedback. I'll look at it we I write the new feature.
