### ISSUE TITLE
Wrong Default User

### ISSUE THREAD

**Issue by BinarMorker** [Youmy001/apine_framework#4]
The default user is defined to be of type 70 in the database, but this type does not exist in the code. The codified type for a default user is 65, and the type for an admin is 77. Because of that, a newly created user is assigned a type that does not correspond to anything, therefore can't be used.

**Comment by Youmy001** [comment]
Thanks your your feedback. The difference between the default type in the database and the user session come from a migration from an older project, from which the Framework originates. All you need to do is to update your database to use the type 65 per default.

A fix will be included in our next commit.
