### ISSUE TITLE
Liste::key_exists() throws a notice on elements with arrays in them

### ISSUE THREAD

**Issue by BinarMorker** [Youmy001/apine_framework#9]
The method `array_diff_assoc` on line 352 in **lib/core/Liste.php** throws a notice when at least one of the two compared objects contain an array. That is because `array_diff_assoc` then treats the object as a multidimentional array, which it does not support. It then gives the following: 

``` Notice: Array to string conversion in lib/core/Liste.php at line 352 ```

A possible fix would be to serialize the objects before passing them into an `array_diff`, then unserializing the result, like this:

``` $diff = array_map('unserialize', array_diff(array_map('serialize', $pageids), array_map('serialize', $parentpage))); ```

**Comment by Youmy001** [comment]
We applied the suggested fix. We'll see how it works before closing the issue.

`$diff = array_map('unserialize', array_diff(array_map('serialize', $array_value), array_map('serialize', $array_item))); `
